name: AWS CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd src
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        cd src
        python -m unittest test_app.py -v

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Deploy Application
      run: |
        sam deploy \
          --stack-name my-first-cicd-app \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides Environment=production \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset